# Generated by Django 3.0.9 on 2020-12-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201208_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
