# Generated by Django 3.0.9 on 2020-12-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
